const actionTypes={
    FETCH_LOGIN_START:"FETCH_LOGIN_START",
    FETCH_LOGIN_SUCCESS:"FETCH_LOGIN_SUCCESS",
    FETCH_LOGIN_REMOVE:"FETCH_LOGIN_REMOVE",
    FETCH_USER_START:"FETCH_USER_START",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_EDIT:"FETCH_USER_EDIT",
    FETCH_USER_ERROR:"FETCH_USER_ERROR",
    FETCH_TODO_START:"FETCH_TODO_START",
    FETCH_TODO_SUCCESS:"FETCH_TODO_SUCCESS",
    FETCH_TODO_ERROR:"FETCH_TODO_ERROR",
    FETCH_USER_REGISTER:"FETCH_USER_REGISTER"
}
export default actionTypes